doubtless:
  target: spark
  outputs:
    spark:
      type: spark
      host: localhost
      method: thrift
      port: 10000
      schema: default
      threads: 4
    postgres:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: doubtless
      schema: default
      threads: 4
