/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doubtless_test_Test */

#ifndef _Included_com_doubtless_test_Test
#define _Included_com_doubtless_test_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_doubtless_test_Test
 * Method:     createBdd
 * Signature:  (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_doubtless_test_Test_createBdd
  (JNIEnv *, jobject, jstring);

/*
 * Class:      com_doubtless_test_Test
 * Method:     bdd2string
 * Signature:  ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_doubtless_test_Test_bdd2string
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:      com_doubtless_test_Test
 * Method:     bddOperator
 * Signature:  (Ljava/lang/String;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_doubtless_test_Test_bddOperator
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:      com_doubtless_test_Test
 * Method:     bddProb
 * Signature:  ([B[B)D
 */
JNIEXPORT jdouble JNICALL Java_com_doubtless_test_Test_bddProb
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:      com_doubtless_test_Test
 * Method:     createDict
 * Signature:  (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_doubtless_test_Test_createDict
  (JNIEnv *, jobject, jstring);

/*
 * Class:      com_doubtless_test_Test
 * Method:     dict2string
 * Signature:  ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_doubtless_test_Test_dict2string
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
