/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      Test
 * Method:     createBdd
 * Signature:  (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Test_createBdd
  (JNIEnv *, jobject, jstring);

/*
 * Class:      Test
 * Method:     bdd2string
 * Signature:  ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_bdd2string
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:      Test
 * Method:     bddOperator
 * Signature:  (Ljava/lang/String;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Test_bddOperator
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
